import type { Application, Client, LicenseTypeTemplate, CaseType } from "@/generated/prisma/client";

export type MergeContext = {
  application: Application & {
    licenseTypeTemplate: LicenseTypeTemplate | null;
    caseType: CaseType | null;
  };
  client: Client;
  staffName: string;
};

type AutoField = {
  key: string;
  label: string;
  resolve: (ctx: MergeContext) => string;
};

// Fixed set of values a Document Template field can auto-map to instead of
// prompting the VA — everything derivable from the Application/Client record
// plus the person generating the document.
export const AUTO_FIELDS: AutoField[] = [
  { key: "client_name", label: "Client Name", resolve: (ctx) => ctx.client.name },
  { key: "client_address", label: "Client Address", resolve: (ctx) => ctx.client.address ?? "" },
  { key: "client_contact", label: "Client Contact Info", resolve: (ctx) => ctx.client.contactInfo ?? "" },
  { key: "application_name", label: "Application Name", resolve: (ctx) => ctx.application.name },
  { key: "license_type", label: "License Type", resolve: (ctx) => ctx.application.licenseTypeTemplate?.name ?? "" },
  { key: "case_type", label: "Case Type", resolve: (ctx) => ctx.application.caseType?.name ?? "" },
  { key: "today", label: "Today's Date", resolve: () => new Date().toLocaleDateString() },
  { key: "staff_name", label: "Staff Name (generated by)", resolve: (ctx) => ctx.staffName },
];

export function resolveAutoField(autoField: string, ctx: MergeContext): string {
  return AUTO_FIELDS.find((f) => f.key === autoField)?.resolve(ctx) ?? "";
}

export const AUTO_FIELD_OPTIONS = AUTO_FIELDS.map((f) => ({ key: f.key, label: f.label }));
