// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations run as the table owner (see src/lib/prisma.ts) — once the
    // app connects as a restricted role, DATABASE_URL can't alter tables.
    url: process.env["SYSTEM_DATABASE_URL"] || process.env["DATABASE_URL"],
  },
});
