"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Download, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { updateGeneratedDocumentStatus, deleteGeneratedDocument } from "@/lib/actions/generated-documents";

type DocumentRow = {
  id: string;
  fileName: string;
  status: "DRAFT" | "APPROVED" | "SENT";
  createdAt: Date;
  template: { name: string };
  generatedBy: { name: string };
};

const STATUS_LABELS = { DRAFT: "Draft", APPROVED: "Approved", SENT: "Sent" } as const;

export function GeneratedDocumentsTable({
  applicationId,
  documents,
  canEdit,
}: {
  applicationId: string;
  documents: DocumentRow[];
  canEdit: boolean;
}) {
  const router = useRouter();
  const [, startTransition] = useTransition();
  const [deletingId, setDeletingId] = useState<string | null>(null);

  function handleStatusChange(id: string, status: "DRAFT" | "APPROVED" | "SENT") {
    startTransition(async () => {
      try {
        await updateGeneratedDocumentStatus(id, applicationId, status);
        router.refresh();
      } catch (error) {
        toast.error(error instanceof Error ? error.message : "Failed to update status");
      }
    });
  }

  function handleDelete(id: string) {
    setDeletingId(id);
    startTransition(async () => {
      try {
        await deleteGeneratedDocument(id, applicationId);
        router.refresh();
      } catch (error) {
        toast.error(error instanceof Error ? error.message : "Failed to delete");
      } finally {
        setDeletingId(null);
      }
    });
  }

  return (
    <div className="overflow-x-auto">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>File</TableHead>
            <TableHead>Template</TableHead>
            <TableHead>Status</TableHead>
            <TableHead>Generated By</TableHead>
            <TableHead>Date</TableHead>
            <TableHead />
          </TableRow>
        </TableHeader>
        <TableBody>
          {documents.length === 0 && (
            <TableRow>
              <TableCell colSpan={6} className="text-center text-muted-foreground">
                No documents generated yet
              </TableCell>
            </TableRow>
          )}
          {documents.map((doc) => (
            <TableRow key={doc.id}>
              <TableCell className="font-medium">{doc.fileName}</TableCell>
              <TableCell className="text-muted-foreground">{doc.template.name}</TableCell>
              <TableCell>
                {canEdit ? (
                  <Select
                    items={STATUS_LABELS}
                    value={doc.status}
                    onValueChange={(v) => handleStatusChange(doc.id, (v ?? "DRAFT") as "DRAFT" | "APPROVED" | "SENT")}
                  >
                    <SelectTrigger size="sm" className="w-[8.5rem]">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="DRAFT">Draft</SelectItem>
                      <SelectItem value="APPROVED">Approved</SelectItem>
                      <SelectItem value="SENT">Sent</SelectItem>
                    </SelectContent>
                  </Select>
                ) : (
                  <span className="text-muted-foreground">{STATUS_LABELS[doc.status]}</span>
                )}
              </TableCell>
              <TableCell className="text-muted-foreground">{doc.generatedBy.name}</TableCell>
              <TableCell className="text-muted-foreground">{new Date(doc.createdAt).toLocaleDateString()}</TableCell>
              <TableCell>
                <div className="flex items-center justify-end gap-1">
                  <Button
                    variant="ghost"
                    size="icon-sm"
                    nativeButton={false}
                    render={<a href={`/api/documents/${doc.id}`} />}
                  >
                    <Download className="size-3.5" />
                  </Button>
                  {canEdit && (
                    <Button
                      variant="ghost"
                      size="icon-sm"
                      disabled={deletingId === doc.id}
                      onClick={() => handleDelete(doc.id)}
                    >
                      <Trash2 className="size-3.5" />
                    </Button>
                  )}
                </div>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}
